### ISSUE TITLE
Load declwidgets init code from bundled dashboard

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#133]
Load all declwidgets resources from the bundle. See the first comment below for more information.

**Tasks:**
* [x] Load `init.js` and `DeclWidgetsModel.js` from bundle.
* [x] Don't build `urth-widgets.js` any more. Remove cloning of declwidgets repo.

---

Previous description:

~~In our Dockerfile.server we're currently relying on  https://github.com/jhpedemonte/declarativewidgets.git@9f6423bbcc4e9e266a8c2594028caeabaebe9a8f in lieu of https://github.com/jupyter-incubator/declarativewidgets/issues/196 getting fixed. This suggests to me that no deploys from a stable declarative widgets release should work. But they did/do when I test with `make dev-with-dashboard-server` in dashboards_bundlers.~~

~~However, when I use a simple docker-compose recipe that installs all stable versions of the jupyter Python packages, sure enough, the errors that @jhpedemonte 's branch is meant to fix shine through.~~

~~I'm missing something ...~~

~~At any rate, we need to first understand what's going on and then, over time, drive the decl widget changes to ensure they work both in the notebook and outside.~~

**Comment by jhpedemonte** [comment]
Paired with @parente and found out that some examples work fine with the non-shimmed declwidgets, while still showing many errors in the console.

But this led us to notice that we are pulling declwidgets resources from 2 areas: (1) the Polymer elements in `urth_components` are bundled with the notebook; (2) the initialization code (`init.js` and `DeclWidgetsModel.js`) are provided directly from the server.  This is a problem because there may be slight mismatch in versions of the two.

Instead, the server should load the init code scripts from the bundle as well. It turns out that the bundler already provides these, in the `urth_widgets` directory (sibling of `urth_components`).

Re-purposing this issue to track the correct loading of declwidgets resources.

**Comment by jhpedemonte** [comment]
Uploaded PR which makes it so we load the DeclWidgets init scripts from the bundle, rather than supplying our own. Of course, this horribly breaks the use of declwidgets, since that code base needs to be updated as well.

**Comment by parente** [comment]
Did you mean to open a PR?

**Comment by jhpedemonte** [comment]
Updated to use newer DeclWidgets init API from https://github.com/jupyter-incubator/declarativewidgets/pull/251.

**Comment by parente** [comment]
Closed by #136.
