### ISSUE TITLE
Redirect to favicon.ico after login

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#161]
Simple fix is probably to use the favicon middleware so that the ico is exposed and passport doesn't think it needs to redirect there instead of the proper / page.

<img width="867" alt="screen shot 2016-03-25 at 9 10 44 am" src="https://cloud.githubusercontent.com/assets/153745/14044706/e3f46100-f269-11e5-9620-a988a9e093b9.png">

**Comment by jhpedemonte** [comment]
Why does passport redirect to `/favicon` instead of `/`?

**Comment by jhpedemonte** [comment]
Odd, I saw this with the docker-compose all-in-one, but not when running from `make dev`.

**Comment by jhpedemonte** [comment]
Added PR that may fix this by serving a favicon. Some things I have found:

1. Browsers will cache the favicon differently than regular cache. To see change, you'll need to restart browser. Even then, if you change the icon, restarting and clearing cache will still show old. Not sure how to reset this cache.
2. The redirect may be tied in to this. I tested on Safari and saw the new icon (from PR). Then when I removed the serving of the favicon, restarted Safari and restarted the server with login set, I saw this error again. But not 100% sure it is fixed since it's very hard to test.

**Comment by jhpedemonte** [comment]
Oh, well found way to do so on Chrome: `rm ~/Library/Application\ Support/Google/Chrome/Default/Favicons`

**Comment by parente** [comment]
> Actually, only happens once per browser, no matter how server is started. Even after clearing cookies/local data, still doesn't go back to /favicon.ico.

Yes. It's odd.

**Comment by jhpedemonte** [comment]
Should we cut a 0.4.1 release for this?

**Comment by parente** [comment]
Your choice. It's just a git tag. Not sure this bug fix warrants one vs all the other bugs we have open.
