### ISSUE TITLE
can I setup dashboarder_server without docker on AWS EC2?

### ISSUE THREAD

**Issue by alexoor** [jupyter-incubator/dashboards_server#257]
This is not an issue, but a question. As I have challenges to setup docker itself, which seems like a prerequisite for dashboard_server.  I think Docker has its value, but I wonder if there is an easy way to setup the dashboard server directly on AWS EC2. 

It will great if there is an example to deploy it on EC2 besides of CF and docker.

**Comment by jhpedemonte** [comment]
Running Dashboards Server doesn't **require** Docker -- we just make use of it in order to aid in development & testing. If you wish to run on AWS, you should be able to install the Dashboards Server and Kernel Gateway directly (along with any prereqs).

Dashboards Server can now be installed using npm: `npm install -g jupyter-dashboards-server`

Kernel Gateway can be installed using pip: `pip install jupyter_kernel_gateway`

**Comment by alexoor** [comment]
Hi, Javier, I really appreciate your quick response. I did not notice jupyter_kernel_gateway is a package required installation. Thanks a lot!

**Comment by parente** [comment]
@alexoor I think you found the https://github.com/jupyter-incubator/dashboards_setup repository already. Still, I wanted to note it here in case others have the same question.
