### ISSUE TITLE
Help needed to configure reversed proxy

### ISSUE THREAD

**Issue by bowenli37** [jupyter-incubator/dashboards_server#307]
Ref #292 

I have read the section in documentation on setting up reversed proxy but was not able to get it working correctly. Just tried to run proxy-container by "make proxy-container". Containers started normally. Visited http://localhost but received 404 error message. I noted that nginx container port 8080 is mapped to host port 80 in Makefile, but nginx is listening on port 80 as in conf file. After changing port 8080 to 80 and rebuilding all 3 container, http://localhost/dashboards_server/ can be reached, but styling was not applied due to missing http://localhost/css/style.css (Failed to load resource).
I was on the latest commit (# 5cac00) by today. What was I missing? Please help! Thanks very much.

**Comment by jhpedemonte** [comment]
You're reading the port mapping incorrectly.  The host port 8080 is mapped to the nginx container's 80 port. Therefore, you have to load from http://localhost:8080. This will show you the default nginx page.

Then, if you load http://localhost:8080/dashboards_server/, you will in fact get an unstyled page. Please review the [proxy section of the README.md](https://github.com/jupyter-incubator/dashboards_server#run-behind-proxy): you have to set a couple of options in `config.json` in order to use the dashboards server behind a proxy.

For use with `make proxy-container`, I set the following options:

    BASE_URL: "[/dashboards_server]"
    TRUST_PROXY: true

**Comment by parente** [comment]
@bowenli37 There hasn't been traffic on this issue for some time so I'm going to close it. If you're still having problems, please reopen it.
