### ISSUE TITLE
Title of every dashboard page is "dashboard"

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#90]
Gets confusing with lots of tabs. The filename would be fine. The first markdown header would be even better.

**Comment by dalogsdon** [comment]
While tackling this, may as well add titles to the home and login pages since neither has a title.

**Comment by jhpedemonte** [comment]
Ideally, I think the algorithm should be something like this:

1. If first cell is markdown, title is the first N characters.
2. File name.

I want to distinguish between "first markdown cell" and "first cell is markdown". If the first cell is non-markdown, we shouldn't skip over it to find the markdown cell in order to pull title. In that case, just use file name.
